plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
    id 'com.google.gms.google-services'
}

android {
    namespace 'luthfi.anggi.e_prestasi'
    compileSdk 35

    defaultConfig {
        applicationId "luthfi.anggi.e_prestasi"
        minSdk 25
        targetSdk 35
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildFeatures {
        viewBinding true
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = '1.8'
    }
}

dependencies {

    implementation 'androidx.core:core-ktx:1.15.0'
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'com.google.android.material:material:1.12.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.2.1'
    implementation 'org.jetbrains.kotlin:kotlin-stdlib:2.1.10'
    implementation 'com.google.android.gms:play-services-cast-framework:22.0.0'

    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.2.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.6.1'

    implementation 'com.google.firebase:firebase-auth-ktx'
    implementation 'com.google.firebase:firebase-firestore-ktx'
    implementation platform('com.google.firebase:firebase-bom:33.10.0')

    implementation 'com.github.dhaval2404:imagepicker:2.1'
    implementation 'com.google.firebase:firebase-storage-ktx'
    implementation 'com.github.bumptech.glide:glide:4.16.0' // Versi terbaru
    annotationProcessor 'com.github.bumptech.glide:compiler:4.16.0'

    implementation 'androidx.cardview:cardview:1.0.0'

    // Midtrans SDK untuk Android
    implementation 'com.midtrans:uikit:2.0.0-SANDBOX'
    implementation 'com.midtrans:uikit:1.23.1'

    // Retrofit dependensi untuk melakukan HTTP request
    implementation 'com.squareup.retrofit2:retrofit:2.9.0'   // Retrofit
    implementation 'com.squareup.retrofit2:converter-gson:2.9.0'  // Converter untuk Gson
    implementation 'com.squareup.retrofit2:converter-scalars:2.9.0'

    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-android:1.5.2'

    implementation "androidx.navigation:navigation-fragment-ktx:2.5.3"
    implementation "androidx.navigation:navigation-ui-ktx:2.5.3"

}